### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by blerude** [royranger/TheScoop#4]
Grade: Meets Expectations

Awesome job on this project! Your code is clean and clear, effectively and efficiently implementing each of the routes. You have a great sense on how to write to the database and you use sophisticated coding language to get the job done. Your code is seamlessly integrated into the codebase you were given as well. 

Moving forward, just be careful about making sure that you properly align and format your code. I also recommend adding comments to detail the purpose of each function and tricky block of code. This is an important habit to develop to show your professionalism, so it never hurts to start now. Again, great job!

**Comment by royranger** [comment]
Thank you!!
